version: "3.7"

services:
  db:
    image: postgres
    container_name: ljs-db
    restart: unless-stopped
    env_file:
      - postgres.env
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pg-data:
    external: true
  